updated

diff --git a/debian-playbook.yml b/debian-playbook.yml
--- a/debian-playbook.yml
+++ b/debian-playbook.yml
@@ -163,7 +163,7 @@
 
     - name: Install linux headers (non-Pi)
       apt:
-        name: "linux-headers-{{ ansible_kernel }}"
+        name: "linux-headers-{{ ansible_facts['kernel'] }}"
         state: present
       when: not is_raspberry and not is_wsl
 
@@ -334,7 +334,7 @@
 
         - name: Download Docker GPG key
           ansible.builtin.get_url:
-            url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
+            url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg"
             dest: /etc/apt/keyrings/docker.asc
             mode: '0644'
             force: true
@@ -348,10 +348,10 @@
             dest: /etc/apt/sources.list.d/docker.sources
             content: |
               Types: deb
-              URIs: https://download.docker.com/linux/{{ ansible_distribution | lower }}
-              Suites: {{ ansible_distribution_release }}
+              URIs: https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}
+              Suites: {{ ansible_facts['distribution_release'] }}
               Components: stable
-              Architectures: {{ arch_mapping[ansible_architecture] }}
+              Architectures: {{ arch_mapping[ansible_facts['architecture']] }}
               Signed-By: /etc/apt/keyrings/docker.gpg
             mode: '0644'
 
@@ -402,20 +402,24 @@
             owner: "{{ target_user_info.uid }}"
             group: "{{ target_user_info.group }}"
 
-    - name: Install Dotfiles
+    - name: Install or Update Dotfiles
       ansible.builtin.shell: |
-        if git clone git@github.com:egandro/dotfiles.git ~/.dotfiles; then
-          cd ~/.dotfiles
-          for d in */ ; do stow --adopt -R "${d%/}" ; done
+        if [ ! -d ~/.dotfiles ]; then
+          if ! git clone git@github.com:egandro/dotfiles.git ~/.dotfiles; then
+            echo "we can't checkout"
+            exit 0
+          fi
         else
-          echo "we can't checkout"
+          cd ~/.dotfiles
+          git pull || echo "we can't update"
         fi
+        cd ~/.dotfiles
+        for d in */ ; do stow --adopt -R "${d%/}" ; done
       become_user: "{{ target_user }}"
       environment:
         HOME: "{{ target_user_home }}"
       args:
         executable: /bin/bash
-        creates: "{{ target_user_home }}/.dotfiles"
 
     - name: Configure Vim
       block:
